# This workflow will build a docker container, publish it to Docker Hub.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for Docker Hub.
#
# 2. Set up secrets in your workspace: DOCKERHUB_KEY with the service account key.
#

name: Build and Deploy to DockerHub

on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  IMAGE: ${{ github.repository }}

jobs:
  setup-build-push:
    name: Setup, Build, Push
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Build the Docker image
    - name: Build
      run: |        
        docker build -t $IMAGE:$(git rev-parse --abbrev-ref $GITHUB_REF) \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" .

    # Push the Docker image to DockerHub
    - name: Push
      run: |
        docker push $IMAGE:$(git rev-parse --abbrev-ref $GITHUB_REF)
        
    - name: Commit Status    
      run: echo TODO
