# This workflow will build a docker container, publish it to Docker Hub.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for Docker Hub.
#
# 2. Set up secrets in your workspace: DOCKERHUB_KEY with the service account key.
#

name: Push to DockerHub

on: 
  push:
    branches: '*'
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build-push:
    name: Push
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master
      
    - name: Build and Push
      uses: ndeloof/docker-action@master
      with:
        password: ${{ secret.DOCKERHUB_PASSWORD }}
